import React from "react";
import Register from "../../components/auth/register";
import { Helmet } from "react-helmet";

const LandingPage = () => {
  return (
    <div>
      <Helmet>
        <title>Create new account</title>
        <meta name="description" content="Generated by create react app" />
        <link rel="icon" href="/favicon.ico" />
      </Helmet>
      <Register />
    </div>
  );
};

export default LandingPage;
