
export const stateData = [
  { id: 0, label: 'Select' },
  { id: 1, label: 'Abia' },
  { id: 2, label: 'Adamawa' },
  { id: 3, label: 'Akwa Ibom' },
  { id: 4, label: 'Anambra' },
  { id: 5, label: 'Bauchi' },
  { id: 6, label: 'Bayelsa' },
  { id: 7, label: 'Benue' },
  { id: 8, label: 'Borno' },
  { id: 9, label: 'Cross River' },
  { id: 10, label: 'Delta' },
  { id: 11, label: 'Ebonyi' },
  { id: 12, label: 'Edo' },
  { id: 13, label: 'Ekiti' },
  { id: 14, label: 'Enugu' },
  { id: 15, label: 'Gombe' },
  { id: 16, label: 'Imo' },
  { id: 17, label: 'Jigawa' },
  { id: 18, label: 'Kaduna' },
  { id: 19, label: 'Kano' },
  { id: 20, label: 'Katsina' },
  { id: 21, label: 'Kebbi' },
  { id: 22, label: 'Kogi' },
  { id: 23, label: 'Kwara' },
  { id: 24, label: 'Lagos' },
  { id: 25, label: 'Nasarawa' },
  { id: 26, label: 'Niger' },
  { id: 27, label: 'Ogun' },
  { id: 28, label: 'Ondo' },
  { id: 29, label: 'Osun' },
  { id: 30, label: 'Oyo' },
  { id: 31, label: 'Plateau' },
  { id: 32, label: 'Rivers' },
  { id: 33, label: 'Sokoto' },
  { id: 34, label: 'Taraba' },
  { id: 35, label: 'Yobe' },
  { id: 36, label: 'Zamfara' },
  { id: 37, label: 'FCT' },
];


export const electionData = [
  {
    id: 1,
    name: "Oyo state general election",
    votes: "176",
    time: "3 hours ago",
    category: "",
    active: true,
  },
  {
    id: 2,
    name: "Oyo state general election",
    votes: "176",
    time: "3 hours ago",
    category: "",
    active: true,
  },
  {
    id: 3,
    name: "Oyo state general election",
    votes: "176",
    time: "3 hours ago",
    category: "",
    active: true,
  },
  {
    id: 4,
    name: "Oyo state general election",
    votes: "176",
    time: "3 hours ago",
    category: "",
    active: true,
  },
  {
    id: 5,
    name: "Oyo state general election",
    votes: "176",
    time: "3 hours ago",
    category: "",
    active: true,
  },
  {
    id: 6,
    name: "Oyo state general election",
    votes: "176",
    time: "3 hours ago",
    category: "",
    active: true,
  },
  {
    id: 7,
    name: "Oyo state general election",
    votes: "176",
    time: "3 hours ago",
    category: "",
    active: true,
  },
  {
    id: 8,
    name: "Oyo state general election",
    votes: "176",
    time: "3 hours ago",
    category: "",
    active: true,
  },
  {
    id: 9,
    name: "Oyo state general election",
    votes: "176",
    time: "3 hours ago",
    category: "",
    active: true,
  },
  {
    id: 10,
    name: "Oyo state general election",
    votes: "176",
    time: "3 hours ago",
    category: "",
    active: false,
  },
]
